biberltd_core_tax_management_manage:
    pattern:  /tax
    defaults: { _controller: BiberLtdBundleTaxManagementBundle:Test:test }
    pattern:  /brand
    defaults: { _controller: BiberLtdBundleProductManagementBundle:Test:test }
