biberltd_core_tax_management_manage:
    pattern:  /tax
    defaults: { _controller: BiberLtdCoreBundlesTaxManagementBundle:Test:test }
    pattern:  /brand
    defaults: { _controller: BiberLtdCoreBundlesProductManagementBundle:Test:test }
